### ISSUE TITLE
Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

### ISSUE THREAD

**Issue by Jeremyyiu** [Jeremyyiu/BatteryManager#31]
Environment: Sony Xperia z2

Steps to reproduce: 
1. Open up app
2. Go to controller tab
3. Crash

Expected Result:
- Work

Actual Result: 
- Crashed, Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

```
 java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
        at android.os.Parcel.readException(Parcel.java:1627)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.call(ContentProviderNative.java:652)
        at android.provider.Settings$NameValueCache.putStringForUser(Settings.java:1326)
        at android.provider.Settings$Secure.putStringForUser(Settings.java:4012)
        at android.provider.Settings$Secure.putIntForUser(Settings.java:4122)
        at android.provider.Settings$Secure.putInt(Settings.java:4116)
        at com.example.jeremy.controller.controller.DisplayController.toggleMonochrome(DisplayController.java:159)
        at com.example.jeremy.controller.controller.DisplayController.init(DisplayController.java:72)
        at com.example.jeremy.controller.ControllerFragment.initDisplayItems(ControllerFragment.java:266)
        at com.example.jeremy.controller.ControllerFragment.initControllerItems(ControllerFragment.java:140)
        at com.example.jeremy.controller.ControllerFragment.onActivityCreated(ControllerFragment.java:126)
        at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2363)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1442)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:234)
        at android.app.ActivityThread.main(ActivityThread.java:5526)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by Jeremyyiu** [comment]
bug fixed - app now asks for permissions upon clicking monochrome, if permissions not given, it ignores the user's request
